# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Lithium"
license = "MIT"
licenselink = "https://github.com/jrutheiser/hugo-lithium-theme/blob/master/LICENSE.md"
description = "Lithium minimal theme"
homepage = "https://github.com/jrutheiser/hugo-lithium-theme"
tags = ["blog"]
features = ["blog", "google analytics"]
min_version = 0.15

[author]
  name = "HYec"
  homepage = "https://hyec.me/"
  repo = "https://github.com/hyec/hugo-theme-lithium"

[original]
  name = "Jonathan Rutheiser"
  homepage = "http://jrutheiser.com/"